### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Michael-F-Ellis** [MonsieurV/ZeroMQ-RPi#1]
The link to the libsodium tarball  is broken.  Perhaps it should be replaced with a link to a suitable release in https://github.com/jedisct1/libsodium/releases ?

**Comment by Michael-F-Ellis** [comment]
The following works:
wget https://github.com/jedisct1/libsodium/releases/download/1.0.3/libsodium-1.0.3.tar.gz

BTW, thanks for publishing this recipe.  It saved me considerable fumbling around!

**Comment by MonsieurV** [comment]
Thanks @Michael-F-Ellis I've updated the link!

Yeah, it's not so obvious from the doc.
